# IMPORTANT NOTE: This is absolutely not safe and it's only meant to simplify the aws tutorial
# we should be using ENV vars to set this value. Please do not use this for a real production app.
production:
  secret_key_base: 5b7076c015bf1a888940a8cc76e1ececac7dd47007eef39625248c1dfc4449296eda54616ea286e83bd07ba75d3a0f950096c67ea6d55634eabd1c9fd71c74ed